[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    regression: Marker for regression tests.
    registration: Marker for tests related to user registration.
    authorization: Marker for tests related to user authorization.
    courses: Marker for tests related to courses.
    dashboard: Marker for tests related to the dashboard.